# Generated by Antigravity

import os
import sys
import time

if sys.stdout.encoding != 'utf-8':
    try:
        sys.stdout.reconfigure(encoding='utf-8')
        sys.stderr.reconfigure(encoding='utf-8')
    except Exception:
        pass

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    classification_report,
    RocCurveDisplay,
    ConfusionMatrixDisplay,
)

# Client modulunu yol listesine ekle
current_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(current_dir)
sys.path.append(os.path.join(current_dir, "client"))
from client_adapter import request_inference


def main():
    print("=" * 60)
    print(">>> TABPFN AS A SERVICE: 5.000 SATIRLIK BENCHMARK TESTI <<<")
    print("=" * 60)

    # 1. Buyuk Boyutlu Sentetik Veri Seti Olusturma
    N_SAMPLES = 5000
    N_FEATURES = 20
    N_TRAIN = 1000
    N_TEST = N_SAMPLES - N_TRAIN

    print(f"\n[1/4] Veri seti olusturuluyor ({N_SAMPLES} satir, {N_FEATURES} ozellik)...")
    X, y = make_classification(
        n_samples=N_SAMPLES,
        n_features=N_FEATURES,
        n_informative=15,
        n_redundant=5,
        n_classes=2,
        random_state=42,
    )

    feature_cols = [f"feature_{i}" for i in range(N_FEATURES)]
    df = pd.DataFrame(X, columns=feature_cols)
    df["target"] = y

    # 2. Gercek Degerleri Saklama ve Test Kismini Maskeleme (-1)
    print(f"[2/4] Veri bolunuyor: {N_TRAIN} satir Train, {N_TEST} satir Test...")
    
    # 4000 test satirinin gercek etiketlerini sakla
    y_true_test = df.loc[N_TRAIN:, "target"].values.copy()

    # Test satirlarinin etiketini -1 olarak maskele
    df.loc[N_TRAIN:, "target"] = -1

    # 3. Istemci Adaptorunu Calistirma ve Sure Olcumu
    print(f"\n[3/4] Istemci adaptoru sunucuya istekleri baslatiyor...")
    print(f"      (800 satir referans baglami, ~{int(np.ceil(N_TEST / 224))} adet test paketi)")
    
    start_time = time.time()
    try:
        result_df = request_inference(
            df=df,
            feature_columns=feature_cols,
            target_column="target",
            target_null_val=-1,
        )
    except Exception as e:
        print(f"\n[!] HATA: Sunucuya baglanilamadi veya bir hata olustu!")
        print(f"Lutfen once sunucunun acik oldugundan emin olun:")
        print(f"Terminalde: cd server && uvicorn server:app --reload --port 8000")
        print(f"\nHata detayi: {e}")
        return

    elapsed_time = time.time() - start_time
    throughput = N_TEST / elapsed_time

    print("\n" + "=" * 60)
    print(f"[OK] CIKARIM TAMAMLANDI!")
    print(f"[*] Toplam Sure:       {elapsed_time:.2f} saniye")
    print(f"[*] Islem Hizi:        {throughput:.1f} ornek/saniye")
    print("=" * 60)

    # 4. Degerlendirme ve Metrikler
    y_pred = result_df["predicted_label"].values
    confidences = result_df["confidence"].values

    # Ikili siniflandirmada Pozitif Sinifin (1) Olasiligini Cikarma
    y_prob_class_1 = np.where(y_pred == 1, confidences, 1.0 - confidences)

    acc = accuracy_score(y_true_test, y_pred)
    auc = roc_auc_score(y_true_test, y_prob_class_1)

    print("\n[+] MODEL PERFORMANS RAPORU:")
    print(f"[*] Dogruluk (Accuracy): %{acc * 100:.2f}")
    print(f"[*] ROC-AUC Skoru:       {auc:.4f}")
    print("\nDetayli Siniflandirma Raporu:")
    print(classification_report(y_true_test, y_pred, digits=4))

    # 5. Gorsellestirme: ROC Curve ve Confusion Matrix
    print("\n[4/4] Grafikler cizdiriliyor...")
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Sol: ROC Egrisi
    RocCurveDisplay.from_predictions(
        y_true_test,
        y_prob_class_1,
        name="TabPFN Zero-Shot",
        ax=axes[0],
    )
    axes[0].plot([0, 1], [0, 1], "k--", label="Rastgele Tahmin (AUC = 0.5)")
    axes[0].set_title(f"ROC Curve (AUC = {auc:.4f})", fontsize=13, fontweight="bold")
    axes[0].grid(True, linestyle="--", alpha=0.6)
    axes[0].legend(loc="lower right")

    # Sag: Karisiklik Matrisi (Confusion Matrix)
    ConfusionMatrixDisplay.from_predictions(
        y_true_test,
        y_pred,
        cmap="Blues",
        ax=axes[1],
        colorbar=False,
    )
    axes[1].set_title(f"Confusion Matrix (Acc = %{acc * 100:.1f})", fontsize=13, fontweight="bold")

    plt.tight_layout()
    plot_path = os.path.join(current_dir, "test_results.png")
    plt.savefig(plot_path, dpi=300)
    print(f"[+] Grafik kaydedildi: {os.path.abspath(plot_path)}")
    plt.show()


if __name__ == "__main__":
    main()
